driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.12.8

platforms:
  - name: centos-5.10
  - name: centos-6.5
  - name: fedora-19
  - name: fedora-20
  - name: ubuntu-10.04
    run_list:
    - recipe[apt]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]

suites:
  - name: default
    run_list: squid
